# Generated by Django 5.1.2 on 2025-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_chatticket_chatticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatticket',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
