# Generated by Django 5.1.2 on 2025-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='YieldCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_density', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('disease_presence', models.BooleanField(default=False)),
                ('pesticide_usage', models.IntegerField(choices=[(0, 'None'), (1, 'Regular'), (2, 'Intensive')])),
                ('field_image', models.ImageField(blank=True, null=True, upload_to='potato_fields/')),
                ('estimated_yield', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
