# Generated by Django 5.1.2 on 2025-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
