# Generated by Django 5.1.2 on 2025-06-26 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='yieldcalculation',
            name='leaf_health_score',
            field=models.FloatField(default=50.0, help_text='Leaf health score (0-100, based on visual assessment)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='yieldcalculation',
            name='potato_image',
            field=models.ImageField(blank=True, help_text='Image of harvested potatoes', null=True, upload_to='potato_images/'),
        ),
        migrations.AddField(
            model_name='yieldcalculation',
            name='potato_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Average potato tuber size', max_length=10),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='disease_presence',
            field=models.BooleanField(default=False, help_text='Presence of diseases like early blight'),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='estimated_yield',
            field=models.FloatField(blank=True, help_text='Calculated yield in tons/acre', null=True),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='field_image',
            field=models.ImageField(blank=True, help_text='Image of the potato field', null=True, upload_to='potato_fields/'),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='nitrogen',
            field=models.FloatField(help_text='Nitrogen applied in kg/acre', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='pesticide_usage',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Regular'), (2, 'Intensive')], default=0, help_text='Level of pesticide usage'),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='phosphorus',
            field=models.FloatField(help_text='Phosphorus applied in kg/acre', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='planting_density',
            field=models.FloatField(help_text='Plants per square foot', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='yieldcalculation',
            name='potassium',
            field=models.FloatField(help_text='Potassium applied in kg/acre', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
