# Generated by Django 5.1.2 on 2025-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_yieldcalculation_leaf_health_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaf_diseases/')),
                ('Choice', models.CharField(choices=[('Bacteria', 'Bacteria'), ('Fungi', 'Fungi'), ('Healthy', 'Healthy'), ('Nematode', 'Nematode'), ('Pest', 'Pest'), ('Phytopthora', 'Phytopthora'), ('Virus', 'Virus')], default='Healthy', max_length=100)),
                ('disease_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
