# Generated by Django 5.1.2 on 2025-02-11 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_chatticketreply_created_on'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='like',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='customer.customer'),
        ),
    ]
